### PR TITLE
Implement error, debug and result printing functions as macros

### PR DESCRIPTION
**Pull request by ajay0**

### CODE REVIEW

**Comment by aero31aero** [comment]
Ping @SrimantaBarua @v-superuser  @basu96

**Review by aero31aero — APPROVED** [review]
LGTM but not sure if using macros is the preferred way of doing such things, thus waiting for another review.

**Comment by ajay0** [comment]
For error functions: Need to print file name and line number along with error message. Using macros one doesn't need to write \__FILE__ and \__LINE__ in every call to the function

**Comment by aero31aero** [comment]
Merged! Thanks @ajay0 !

**Pull request merged**
