### PR TITLE
Contest

### PR DESCRIPTION
**Pull request by dub-basu**
Added Submissions.
Executables can now be executed safely in the sandbox, thanks to @ajay0 
Frontend added by @ankit0905

### CODE REVIEW

**Comment by aero31aero** [comment]
What's up with the conflicts here? Can these be resolved by you?

**Comment by dub-basu** [comment]
I'll review tonight and fix them.

**Comment by aero31aero** [comment]
Cool. I'll merge these changes in then. Please try to make small PRs that are easy to review from the next time. :)

**Comment by dub-basu** [comment]
Noted.

**Comment by SrimantaBarua** [comment]
@ankit0905 @ajay0 , it's better if you send in your features as independent PRs. Merging this might take time.
@basu96 , you sort of need to clean this up. There are a few unnecessary files here (a few a.out s for example). Try using .gitignore files.

**Comment by aero31aero** [comment]
All the commits have been merged. Thanks @ajay0 and @basu96!

**Pull request closed without merging**
